from __future__ import annotations

import os
from dataclasses import dataclass


@dataclass(frozen=True)
class Source:
    name: str
    category: str
    feed_url: str
    homepage: str
    region: str = "global"
    kind: str = "feed"
    parser: str = ""


SOURCES: list[Source] = [
    Source(
        name="BBC World",
        category="world",
        feed_url="https://feeds.bbci.co.uk/news/world/rss.xml",
        homepage="https://www.bbc.com/news/world",
        region="global",
    ),
    Source(
        name="BBC Business",
        category="business",
        feed_url="https://feeds.bbci.co.uk/news/business/rss.xml",
        homepage="https://www.bbc.com/news/business",
        region="global",
    ),
    Source(
        name="NPR Business",
        category="business",
        feed_url="https://feeds.npr.org/1006/rss.xml",
        homepage="https://www.npr.org/sections/business/",
        region="us",
    ),
    Source(
        name="CNBC World",
        category="markets",
        feed_url="https://www.cnbc.com/id/100727362/device/rss/rss.html",
        homepage="https://www.cnbc.com/world/",
        region="global",
    ),
    Source(
        name="CNBC Economy",
        category="macro",
        feed_url="https://www.cnbc.com/id/20910258/device/rss/rss.html",
        homepage="https://www.cnbc.com/economy/",
        region="us",
    ),
    Source(
        name="MarketWatch Top Stories",
        category="markets",
        feed_url="https://feeds.content.dowjones.io/public/rss/mw_topstories",
        homepage="https://www.marketwatch.com/",
        region="us",
    ),
    Source(
        name="Federal Reserve Press Releases",
        category="policy",
        feed_url="https://www.federalreserve.gov/feeds/press_all.xml",
        homepage="https://www.federalreserve.gov/newsevents/pressreleases.htm",
        region="us",
    ),
    Source(
        name="Federal Reserve Monetary Policy",
        category="policy",
        feed_url="https://www.federalreserve.gov/feeds/press_monetary.xml",
        homepage="https://www.federalreserve.gov/monetarypolicy.htm",
        region="us",
    ),
    Source(
        name="Federal Reserve Speeches and Testimony",
        category="policy",
        feed_url="https://www.federalreserve.gov/feeds/speeches_and_testimony.xml",
        homepage="https://www.federalreserve.gov/newsevents/speeches-testimony.htm",
        region="us",
    ),
    Source(
        name="Federal Reserve Board Meetings",
        category="policy",
        feed_url="https://www.federalreserve.gov/feeds/boardmeetings.xml",
        homepage="https://www.federalreserve.gov/newsevents/calendar.htm",
        region="us",
    ),
    Source(
        name="Atlanta Fed GDPNow",
        category="macro",
        feed_url="https://www.atlantafed.org/rss/GDPNow",
        homepage="https://www.atlantafed.org/cqer/research/gdpnow",
        region="us",
    ),
    Source(
        name="Atlanta Fed Market Probability Tracker",
        category="policy",
        feed_url="https://www.atlantafed.org/rss/MarketProbabilityTracker",
        homepage="https://www.atlantafed.org/cenfis/market-probability-tracker",
        region="us",
    ),
    Source(
        name="Atlanta Fed Speeches",
        category="policy",
        feed_url="https://www.atlantafed.org/rss/speechindex",
        homepage="https://www.atlantafed.org/news/speeches",
        region="us",
    ),
    Source(
        name="Atlanta Fed Press Releases",
        category="policy",
        feed_url="https://www.atlantafed.org/rss/pressindex",
        homepage="https://www.atlantafed.org/news/pressreleases",
        region="us",
    ),
    Source(
        name="SEC Press Releases",
        category="regulation",
        feed_url="https://www.sec.gov/news/pressreleases.rss",
        homepage="https://www.sec.gov/news/pressreleases",
        region="us",
    ),
    Source(
        name="SEC Latest 8-K Filings",
        category="filings",
        feed_url="https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&company=&count=40&dateb=&output=atom&owner=include&start=0&type=8-k",
        homepage="https://www.sec.gov/search-filings",
        region="us",
    ),
    Source(
        name="BLS CPI Releases",
        category="macro",
        feed_url="https://www.bls.gov/feed/cpi.rss",
        homepage="https://www.bls.gov/cpi/news.htm",
        region="us",
    ),
    Source(
        name="BLS PPI Releases",
        category="macro",
        feed_url="https://www.bls.gov/feed/ppi.rss",
        homepage="https://www.bls.gov/ppi/news-release/",
        region="us",
    ),
    Source(
        name="EIA Press Releases",
        category="energy",
        feed_url="https://www.eia.gov/rss/press_rss.xml",
        homepage="https://www.eia.gov/pressroom/",
        region="us",
    ),
    Source(
        name="EIA Today in Energy",
        category="energy",
        feed_url="https://www.eia.gov/rss/todayinenergy.xml",
        homepage="https://www.eia.gov/todayinenergy/",
        region="us",
    ),
    Source(
        name="EIA Gasoline and Diesel Fuel Update",
        category="energy",
        feed_url="https://www.eia.gov/petroleum/gasdiesel/includes/gas_diesel_rss.xml",
        homepage="https://www.eia.gov/petroleum/gasdiesel/",
        region="us",
    ),
    Source(
        name="EIA Congressional Testimony",
        category="energy",
        feed_url="https://www.eia.gov/rss/testimony.xml",
        homepage="https://www.eia.gov/pressroom/testimony.php",
        region="us",
    ),
    Source(
        name="IMF News",
        category="macro",
        feed_url="https://www.imf.org/en/News/RSS",
        homepage="https://www.imf.org/en/News",
        region="global",
    ),
    Source(
        name="ECB Press",
        category="policy",
        feed_url="https://www.ecb.europa.eu/rss/press.html",
        homepage="https://www.ecb.europa.eu/press/html/index.en.html",
        region="europe",
    ),
    Source(
        name="ECB Market Operations",
        category="policy",
        feed_url="https://www.ecb.europa.eu/rss/operations.html",
        homepage="https://www.ecb.europa.eu/mopo/implement/html/index.en.html",
        region="europe",
    ),
    Source(
        name="Bank of England News",
        category="policy",
        feed_url="https://www.bankofengland.co.uk/rss/news",
        homepage="https://www.bankofengland.co.uk/news",
        region="europe",
    ),
    Source(
        name="Bank of England Speeches",
        category="policy",
        feed_url="https://www.bankofengland.co.uk/rss/speeches",
        homepage="https://www.bankofengland.co.uk/news/speeches",
        region="europe",
    ),
    Source(
        name="Bank of England Prudential Regulation Publications",
        category="regulation",
        feed_url="https://www.bankofengland.co.uk/rss/prudential-regulation-publications",
        homepage="https://www.bankofengland.co.uk/prudential-regulation/publication",
        region="europe",
    ),
    Source(
        name="CFTC General Press Releases",
        category="regulation",
        feed_url="https://www.cftc.gov/RSS/RSSGP/rssgp.xml",
        homepage="https://www.cftc.gov/PressRoom/PressReleases",
        region="us",
    ),
    Source(
        name="CFTC Enforcement Press Releases",
        category="regulation",
        feed_url="https://www.cftc.gov/RSS/RSSENF/rssenf.xml",
        homepage="https://www.cftc.gov/PressRoom/PressReleases",
        region="us",
    ),
    Source(
        name="CFTC Speeches and Testimony",
        category="regulation",
        feed_url="https://www.cftc.gov/RSS/RSSST/rssst.xml",
        homepage="https://www.cftc.gov/PressRoom/SpeechesTestimony",
        region="us",
    ),
    Source(
        name="Treasury Offering Announcements",
        category="macro",
        feed_url="https://treasurydirect.gov/TA_WS/securities/announced/rss",
        homepage="https://treasurydirect.gov/auctions/announcements-data-results/",
        region="us",
    ),
    Source(
        name="Treasury Auction Results",
        category="markets",
        feed_url="https://treasurydirect.gov/TA_WS/securities/auctioned/rss",
        homepage="https://treasurydirect.gov/auctions/announcements-data-results/",
        region="us",
    ),
    Source(
        name="CME Interest Rates Commentary",
        category="markets",
        feed_url="https://www.cmegroup.com/rss/interestrates-video-commentary.rss",
        homepage="https://www.cmegroup.com/markets/interest-rates.html",
        region="us",
    ),
    Source(
        name="CME Metals Commentary",
        category="markets",
        feed_url="https://www.cmegroup.com/rss/metals-video-commentary.rss",
        homepage="https://www.cmegroup.com/markets/metals.html",
        region="global",
    ),
    Source(
        name="CME Interest Rate Releases",
        category="macro",
        feed_url="https://feeds.feedburner.com/EconomicEventsInterestRates",
        homepage="https://www.cmegroup.com/markets/interest-rates.html",
        region="us",
    ),
    Source(
        name="CME FX Commentary",
        category="markets",
        feed_url="https://www.cmegroup.com/rss/fx-video-commentary.rss",
        homepage="https://www.cmegroup.com/markets/fx.html",
        region="global",
    ),
    Source(
        name="NVIDIA Newsroom",
        category="markets",
        feed_url="https://nvidianews.nvidia.com/releases.xml",
        homepage="https://nvidianews.nvidia.com/",
        region="us",
    ),
    Source(
        name="NVIDIA Blog",
        category="markets",
        feed_url="https://feeds.feedburner.com/nvidiablog",
        homepage="https://blogs.nvidia.com/",
        region="us",
    ),
    Source(
        name="Al Jazeera News",
        category="world",
        feed_url="https://www.aljazeera.com/xml/rss/all.xml",
        homepage="https://www.aljazeera.com/",
        region="middle-east",
    ),
    Source(
        name="CoinDesk Markets",
        category="markets",
        feed_url="https://www.coindesk.com/arc/outboundfeeds/rss/?outputType=xml",
        homepage="https://www.coindesk.com/markets/",
        region="global",
    ),
    Source(
        name="White House News",
        category="policy",
        feed_url="https://www.whitehouse.gov/news/",
        homepage="https://www.whitehouse.gov/news/",
        region="us",
        kind="html",
        parser="whitehouse_news",
    ),
    Source(
        name="USTR Press Releases",
        category="policy",
        feed_url="https://ustr.gov/about-us/policy-offices/press-office/press-releases",
        homepage="https://ustr.gov/about-us/policy-offices/press-office/press-releases",
        region="us",
        kind="html",
        parser="ustr_press",
    ),
]


MARKET_KEYWORDS: tuple[str, ...] = (
    "fed",
    "federal reserve",
    "interest rate",
    "inflation",
    "cpi",
    "ppi",
    "jobs",
    "nonfarm",
    "payroll",
    "gdp",
    "recession",
    "treasury",
    "yield",
    "bond",
    "dollar",
    "dxy",
    "foreign exchange",
    "fx",
    "forex",
    "yen",
    "euro",
    "sterling",
    "yuan",
    "renminbi",
    "treasury auction",
    "auction result",
    "refunding",
    "coupon",
    "tips",
    "floating rate note",
    "bill auction",
    "note auction",
    "bond auction",
    "gold",
    "silver",
    "platinum",
    "palladium",
    "copper",
    "bullion",
    "precious metal",
    "metals",
    "tariff",
    "sanction",
    "oil",
    "opec",
    "gas",
    "energy",
    "war",
    "military",
    "missile",
    "attack",
    "china",
    "taiwan",
    "russia",
    "ukraine",
    "middle east",
    "iran",
    "israel",
    "shipping",
    "strait",
    "bank",
    "liquidity",
    "default",
    "debt",
    "downgrade",
    "guidance",
    "earnings",
    "merger",
    "acquisition",
    "probe",
    "antitrust",
    "sec",
    "doj",
    "fda",
    "export control",
    "chip",
    "semiconductor",
    "nvidia",
    "jensen huang",
    "gtc",
    "gpu technology conference",
    "keynote",
    "blackwell",
    "grace blackwell",
    "cuda",
    "dgx",
    "apple",
    "microsoft",
    "tesla",
    "amazon",
    "meta",
    "google",
    "bitcoin",
    "ethereum",
    "crypto",
    "8-k",
    "10-k",
    "10-q",
    "annual report",
    "quarterly report",
    "petroleum",
    "gasoline",
    "diesel",
    "propane",
    "natural gas",
    "storage report",
    "fomc",
    "beige book",
    "powell",
    "minutes",
)


MARKET_SYMBOLS: tuple[str, ...] = (
    "s&p",
    "nasdaq",
    "dow",
    "vix",
    "wti",
    "brent",
    "dollar index",
    "u.s. dollar",
    "usd",
    "dxy",
    "eurusd",
    "usdjpy",
    "gbpusd",
    "usdcny",
    "usd/cny",
    "eur/usd",
    "usd/jpy",
    "gbp/usd",
    "2-year treasury",
    "10-year treasury",
    "30-year treasury",
    "2-year yield",
    "10-year yield",
    "30-year yield",
    "treasury yield",
    "bond yield",
    "real yield",
    "tips yield",
    "us10y",
    "us02y",
    "us30y",
    "gold futures",
    "silver futures",
    "spot gold",
    "spot silver",
)


POLL_INTERVAL_SECONDS = int(os.getenv("MARKET_STREAM_POLL_INTERVAL_SECONDS", "60"))
MAX_ITEMS = int(os.getenv("MARKET_STREAM_MAX_ITEMS", "250"))
DB_PATH = os.getenv("MARKET_STREAM_DB_PATH", "data/market_stream.db")
MAX_STORED_ITEMS = int(os.getenv("MARKET_STREAM_MAX_STORED_ITEMS", "100000"))
CLASSIFIER_MODE = os.getenv("MARKET_STREAM_CLASSIFIER_MODE", "heuristic")
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://127.0.0.1:11434")
OLLAMA_MODEL = os.getenv("MARKET_STREAM_OLLAMA_MODEL", "deepseek-r1:8b")
OLLAMA_TIMEOUT_SECONDS = float(os.getenv("MARKET_STREAM_OLLAMA_TIMEOUT_SECONDS", "20"))

SEC_ALWAYS_KEEP_FORMS: tuple[str, ...] = (
    "8-k",
    "8-k/a",
)

SEC_EVENT_KEYWORDS: tuple[str, ...] = (
    "earnings",
    "results",
    "guidance",
    "merger",
    "acquisition",
    "bankruptcy",
    "restructuring",
    "investigation",
    "regulation fd disclosure",
    "completion of acquisition",
    "entry into a material definitive agreement",
    "termination of a material definitive agreement",
    "financial statements and exhibits",
    "creation of a direct financial obligation",
    "costs associated with exit or disposal activities",
    "material impairments",
    "notice of delisting",
    "material definitive agreement",
    "departure of directors",
    "departure of certain officers",
    "other events",
    "delisting",
    "default",
    "impairment",
    "offering",
    "share repurchase",
    "dividend",
)


CATEGORY_LABELS: dict[str, str] = {
    "world": "Global",
    "business": "Business",
    "markets": "Markets",
    "macro": "Macro",
    "policy": "Policy",
    "regulation": "Regulation",
    "filings": "Filings",
    "energy": "Energy",
}


RETAIL_WATCHLIST: dict[str, tuple[str, ...]] = {
    "NVDA": ("nvda", "nvidia"),
    "TSLA": ("tsla", "tesla"),
    "AAPL": ("aapl", "apple"),
    "MSFT": ("msft", "microsoft"),
    "META": ("meta", "facebook", "instagram"),
    "GOOGL": ("googl", "goog", "alphabet", "google"),
    "AMZN": ("amzn", "amazon"),
}

# Snapshot source: Stock Titan "Largest Companies by Market Cap — March 2026"
# Retrieved on 2026-03-26 and used only to gate SEC 8-K ingestion.
TOP_100_MARKET_CAP_ISSUERS: dict[str, str] = {
    "NVDA": "NVIDIA Corp",
    "AAPL": "Apple Inc",
    "GOOGL": "Alphabet Inc",
    "GOOG": "Alphabet Inc",
    "MSFT": "Microsoft Corporation",
    "AMZN": "Amazon.com Inc.",
    "TSM": "Taiwan Semiconductor Manufacturing Co Ltd",
    "META": "Meta Platforms Inc",
    "AVGO": "Broadcom Inc",
    "TSLA": "Tesla Inc",
    "BRK.A": "Berkshire Hathaway Inc.",
    "BRK.B": "Berkshire Hathaway Inc.",
    "WMT": "Walmart Inc",
    "LLY": "Eli Lilly and Co",
    "JPM": "JPMorgan Chase and Co.",
    "XOM": "Exxon Mobil Corp.",
    "V": "Visa Inc",
    "JNJ": "Johnson and Johnson",
    "ASML": "ASML Holding NV",
    "MU": "Micron Technology Inc.",
    "MA": "Mastercard Incorporated",
    "ORCL": "Oracle Corp.",
    "COST": "Costco Wholesale Corp",
    "CVX": "Chevron Corp.",
    "NFLX": "Netflix Inc.",
    "PLTR": "Palantir Technologies Inc",
    "ABBV": "AbbVie Inc",
    "BAC": "Bank of America Corp.",
    "PG": "Procter and Gamble Co.",
    "AMD": "Advanced Micro Devices Inc.",
    "HD": "Home Depot Inc.",
    "CAT": "Caterpillar Inc.",
    "KO": "Coca-Cola Co",
    "CSCO": "Cisco Systems Inc.",
    "GE": "General Electric Co.",
    "BABA": "Alibaba Group Holding Ltd",
    "LRCX": "Lam Research Corp.",
    "AMAT": "Applied Materials Inc.",
    "MRK": "Merck and Co Inc",
    "AZN": "AstraZeneca plc",
    "NVS": "Novartis AG",
    "TM": "Toyota Motor Corporation",
    "HSBC": "HSBC Holdings plc",
    "RTX": "RTX Corp",
    "MS": "Morgan Stanley",
    "SHEL": "Shell Plc",
    "PM": "Philip Morris International Inc.",
    "GS": "Goldman Sachs Group Inc.",
    "UNH": "UnitedHealth Group Inc",
    "WFC": "Wells Fargo and Co.",
    "GEV": "GE Vernova Inc.",
    "IBM": "International Business Machines Corp.",
    "TMUS": "T-Mobile US Inc",
    "RY": "Royal Bank of Canada",
    "LIN": "Linde Plc.",
    "INTC": "Intel Corp.",
    "MCD": "McDonald's Corp",
    "VZ": "Verizon Communications Inc",
    "SAP": "SAP SE",
    "AXP": "American Express Co.",
    "PEP": "PepsiCo Inc",
    "T": "AT&T Inc.",
    "KLAC": "KLA Corp.",
    "C": "Citigroup Inc",
    "TTE": "TotalEnergies SE",
    "AMGN": "Amgen Inc.",
    "MUFG": "Mitsubishi UFJ Financial Group Inc.",
    "NEE": "NextEra Energy Inc",
    "ABT": "Abbott Laboratories",
    "CRM": "Salesforce Inc",
    "TMO": "Thermo Fisher Scientific Inc.",
    "TJX": "TJX Companies Inc.",
    "DIS": "Walt Disney Co",
    "BHP": "BHP Group Limited",
    "TXN": "Texas Instruments Inc.",
    "ANET": "Arista Networks Inc",
    "GILD": "Gilead Sciences Inc.",
    "ISRG": "Intuitive Surgical Inc",
    "SCHW": "Charles Schwab Corp.",
    "NVO": "Novo Nordisk",
    "SAN": "Banco Santander S.A.",
    "APH": "Amphenol Corp.",
    "SHOP": "Shopify Inc",
    "TD": "Toronto Dominion Bank",
    "BA": "Boeing Co.",
    "COP": "ConocoPhillips",
    "APP": "AppLovin Corp",
    "UBER": "Uber Technologies Inc",
    "DE": "Deere and Co.",
    "ADI": "Analog Devices Inc.",
    "PFE": "Pfizer Inc.",
    "BLK": "BlackRock Inc.",
    "ARM": "Arm Holdings plc.",
    "LMT": "Lockheed Martin Corp.",
    "HON": "Honeywell International Inc",
    "UNP": "Union Pacific Corp.",
    "ETN": "Eaton Corporation plc",
    "RIO": "Rio Tinto plc",
    "BKNG": "Booking Holdings Inc",
    "QCOM": "Qualcomm Inc.",
}
